# Generate the Verilog build metadata include before synthesis.
#
# From a Vivado Tcl console or build script:
#   source O:/fpga/scripts/generate_build_info.tcl
#
# Optional version override before sourcing:
#   set build_info_version_major 1
#   set build_info_version_minor 2
#   set build_info_version_patch 3

set script_dir [file dirname [file normalize [info script]]]
set repo_root [file normalize [file join $script_dir .. ..]]
set output_file [file join $repo_root fpga rtl common build_info build_info_regs.vh]

if {![info exists build_info_version_major]} { set build_info_version_major 0 }
if {![info exists build_info_version_minor]} { set build_info_version_minor 1 }
if {![info exists build_info_version_patch]} { set build_info_version_patch 0 }

foreach {name value maximum} [list \
    major $build_info_version_major 255 \
    minor $build_info_version_minor 255 \
    patch $build_info_version_patch 65535] {
  if {![string is integer -strict $value] || $value < 0 || $value > $maximum} {
    error "Invalid $name version component '$value' (expected 0..$maximum)"
  }
}

set version [expr {($build_info_version_major << 24) |
                   ($build_info_version_minor << 16) |
                   $build_info_version_patch}]

if {[catch {exec git -C $repo_root rev-parse --verify HEAD} full_hash]} {
  error "Cannot determine Git commit for $repo_root: $full_hash"
}
set git_hash [string toupper [string range [string trim $full_hash] 0 7]]

if {[catch {exec git -C $repo_root status --porcelain --untracked-files=normal} status]} {
  error "Cannot determine Git worktree state for $repo_root: $status"
}

# The generated header and disposable build products do not make the source
# tree dirty. Every other tracked modification or untracked path does.
set dirty 0
foreach line [split [string trim $status] "\n"] {
  set normalized [string map {"\\" "/"} [string trim $line]]
  if {$normalized eq "" ||
      [string match "?? build/" $normalized] ||
      [string match "* fpga/rtl/common/build_info/build_info_regs.vh" $normalized]} {
    continue
  }
  set dirty 1
  break
}

set build_date [clock format [clock seconds] -format %Y%m%d]
set build_time [clock format [clock seconds] -format %H%M%S]

file mkdir [file dirname $output_file]
set fd [open $output_file w]
puts $fd {`ifndef BUILD_INFO_REGS_VH}
puts $fd {`define BUILD_INFO_REGS_VH}
puts $fd {}
puts $fd {// Generated by fpga/scripts/generate_build_info.tcl. Do not edit.}
puts $fd [format {`define BUILD_INFO_MAGIC            32'h4F46444D}]
puts $fd [format {`define BUILD_INFO_PROJECT_VERSION  32'h%08X} $version]
puts $fd [format {`define BUILD_INFO_GIT_HASH         32'h%s} $git_hash]
puts $fd [format {`define BUILD_INFO_BUILD_DATE       32'd%s} $build_date]
puts $fd [format {`define BUILD_INFO_BUILD_TIME       32'd%s} $build_time]
puts $fd [format {`define BUILD_INFO_DIRTY_FLAG       32'd%d} $dirty]
puts $fd {}
puts $fd {`endif}
close $fd

puts [format "Generated %s: v%d.%d.%d git=%s date=%s time=%s dirty=%d" \
  $output_file \
  $build_info_version_major $build_info_version_minor $build_info_version_patch \
  $git_hash $build_date $build_time $dirty]
