`ifndef BUILD_INFO_REGS_VH
`define BUILD_INFO_REGS_VH

// Generated by fpga/scripts/generate_build_info.tcl. Do not edit.
`define BUILD_INFO_MAGIC            32'h4F46444D
`define BUILD_INFO_PROJECT_VERSION  32'h00010000
`define BUILD_INFO_GIT_HASH         32'hAC4BDB98
`define BUILD_INFO_BUILD_DATE       32'd20260917
`define BUILD_INFO_BUILD_TIME       32'd080741
`define BUILD_INFO_DIRTY_FLAG       32'd1

`endif
